<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAL\DalFacade\DalFacade.csproj" />
    <ProjectReference Include="..\DAL\DalList\DalList.csproj" />
  </ItemGroup>

</Project>
