<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BlImplementation\ProductImplementation.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="BlImplementation\ProductImplementation.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DalFacade\DalFacade.csproj" />
    <ProjectReference Include="..\DalList\DalList.csproj" />
  </ItemGroup>

</Project>
